### ISSUE TITLE
"incorrect PubKey" 

### ISSUE THREAD

**Issue by EvgeniyTaburyanskiy** [MinterTeam/minter-php-sdk#12]
Пытаюсь сделать DeclareCandidacy .
В данных делаю:
'pubkey' => SDK\MinterWallet::privateToPublic($arWallet_Node['private_key']),

Ответ от сервера
{"code":407,"log":"Check tx error: Incorrect PubKey"}

Это появилось после сегодняшнего обновления.
До обновления сервер принимал ключ нормально!

**Comment by GrKamil** [comment]
privateToPublic was return the public key without the Prefix.
Fixed.

**Comment by EvgeniyTaburyanskiy** [comment]
Легче не стало.
Нода все равно отдает туже ошибку
{"code":407,"log":"Check tx error: Incorrect PubKey"}

**Comment by danil-lashin** [comment]
@EvgeniyTaburyanskiy , кандидаты используют иные публичные ключи. Чуть позже обновим документацию.
