### ISSUE TITLE
$tx->getFee() возвращает не соотвествующую реальности комиссию

### ISSUE THREAD

**Issue by vanlikk** [MinterTeam/minter-php-sdk#18]
$tx->getFee() возвращает не соотвествующую реальности комиссию.

Комиссия для проведения транзакции согласно коду: 
  ```
      $tx = new MinterTx([
            'nonce' => $nonce,
            'gasPrice' => 1,
            'type' => MinterSendCoinTx::TYPE,
            'data' => [
                 'coin' => 'MNT',
                  'to' => $receiverWallet,
               'value' => '2.1'
          ],
            'payload' => '',
            'serviceData' => ''
        ]);
		echo "Fee between accounts: ".$tx->getFee()."\n";
```
выдает 1000000000000000000000000
хотя по факту это значение равно 100000000000000000 . можно увидеть  сколько снимается при проведении транзакции через vault 

так же несоотвествие для процедуры delegate: 
Код 
```

		$tx = new MinterTx([
			'nonce' => $nonce,
			'gasPrice' => 1,
			'type' => MinterDelegateTx::TYPE,
			'data' => [
				'coin' => 'MNT',
				'pubkey' => $pubkey,
				'stake' => '1'
			],
			'payload' => '',
			'serviceData' => ''
		]);

		echo "Delegation Fee: ".$tx->getFee()."\n";
```
возвращает : Delegation Fee: 10000000000000000000000000, а по факту стоимость такой транзакции  1000000000000000000 MNT . если смотреть в https://github.com/MinterTeam/minter-php-sdk/blob/master/src/Minter/SDK/MinterCoins/MinterDelegateTx.php то там установлена стоимость в PIP  " const COMMISSION = '100000000000000000';" , что не сравнимо ни с одним из значений.

Полный код программы: https://pastebin.com/2d89fEDm

**Comment by GrKamil** [comment]
Исправлено вместе с последним обновлением комиссий. 

https://github.com/MinterTeam/minter-php-sdk/commit/140367b7b6b86718bb7dc0a9db6fe78b23c9d3e0
