### ISSUE TITLE
getHash() Не верно рассчитывает хеш

### ISSUE THREAD

**Issue by EvgeniyTaburyanskiy** [MinterTeam/minter-php-sdk#23]
Сделал транзакцию , получил Хеш в SDK PHP
Mt52623a967982504f4a156d2789e2da7b627684f9

Но в блокчейне эта транзакция имеет иной хеш
https://testnet.explorer.minter.network/transactions/Mt2aae4013f18b6e77cb078629f7e5ac565b8bc2c1

**Comment by GrKamil** [comment]
Тендерминт обновил алгоритм вычисления хеша. Метод тоже обновили.
