### ISSUE TITLE
MinterDelegateTx should accept PIPs as stake amount, not BIP

### ISSUE THREAD

**Issue by ingria** [MinterTeam/minter-php-sdk#31]
It should be bigint, as stated in the [docs](https://minter-go-node.readthedocs.io/en/latest/transactions.html#delegate-transaction).

Now, to delegate 1 BIP the payload is:

```
'data' => [
    'stake' => '1',
],
```

Should be:
```
'data' => [
    'stake' => '1000000000000000000',
],
```

**Comment by GrKamil** [comment]
@ingria SDK converts stake to PIP before the signing itself.

**Comment by ingria** [comment]
No. If I create the transaction with number `1000000000000000000` as amount, it's got converted to `1000000000000000000000000000000000000` under the hood. Obviously, it won't work.

But if I use `1` as amount, it's converted to `1000000000000000000` and everything works as expected.

**Comment by GrKamil** [comment]
Using PHP SDK, you need pass BIP (or any coin) as the input, not PIP. (it is much simpler, because it dont need to convert by yourself). 
SDK will convert it to the PIP, before signing.

**Comment by ingria** [comment]
@GrKamil this approach makes impossible sending less then 1 BIP, and adds necessity to calculate commission separately (if amount - commission < 1, SDK will fail).

Also it creates inconsistency with the [docs](https://minter-go-node.readthedocs.io/en/latest/transactions.html#delegate-transaction).
