### ISSUE TITLE
Error in MinterSendCoinTx

### ISSUE THREAD

**Issue by oggy95** [MinterTeam/minter-php-sdk#85]
Hello. Try to create MinterSendCoinTx and got an error:
`$data = new MinterSendCoinTx(0, $to, (string)$amount);`

`2020-10-21 08:32:17 [95.217.152.178][-][-][error][yii\base\ErrorException:64] yii\base\ErrorException: Declaration of Minter\SDK\MinterCoins\MinterSendCoinTx::encode(): array must be compatible with Minter\SDK\MinterCoins\MinterCoinTx::encode(): Web3p\RLP\Buffer in /var/www/cripto_service/vendor/minter/minter-php-sdk/src/Minter/SDK/MinterCoins/MinterSendCoinTx.php:13`

PHP 7.2.24-1+0-20191026.31+debian9-1.gbpbbacde (cli) (built: Oct 26 2019 14:18:28) ( NTS )
"minter/minter-php-sdk": "dev-master"

**Comment by GrKamil** [comment]
Do you use the last version of SDK?

**Comment by oggy95** [comment]
Oh, sorry, all good. Have an issue with composer, not all packages of sdk were updated :)
