### ISSUE TITLE
BIP ID

### ISSUE THREAD

**Issue by QuietAko** [MinterTeam/minter-php-sdk#89]
What is the ID for the BIP ?

**Comment by GrKamil** [comment]
ID: 0

**Comment by QuietAko** [comment]
> ID: 0

But when I requested to https://node-api.testnet.minter.network/v2/coin_info_by_id/0
it returned to me coin symbol is MNT ?

**Comment by GrKamil** [comment]
Because your request in testnet network 
In mainnet it will be BIP
