### ISSUE TITLE
Main net 

### ISSUE THREAD

**Issue by QuietAko** [MinterTeam/minter-php-sdk#90]
Какие ссылки для api main net ?

**Comment by GrKamil** [comment]
Официальных нод нет. Вы можете поднять свою или использовать публичные, например:
1. https://funfasy.dev/
2. https://api.minter.one/v2

**Comment by QuietAko** [comment]
> Официальных нод нет. Вы можете поднять свою или использовать публичные, например:
> 
> 1. https://funfasy.dev/
> 2. https://api.minter.one/v2

Спасибо, а есть какое-то руководство по поднятию своего main net ?

**Comment by GrKamil** [comment]
https://www.minter.network/docs
